Traceback (most recent call last):
  File "/mnt/iusers01/rb01/m60623zk/bin/PairNetOpsV3/network.py", line 513, in <module>
    main()
  File "/mnt/iusers01/rb01/m60623zk/bin/PairNetOpsV3/network.py", line 496, in main
    train_loss = train(model,train_loader,n_train,optimizer,device,loss_weights,loss_fn,n_atoms)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/iusers01/rb01/m60623zk/bin/PairNetOpsV3/network.py", line 316, in train
    outputs = model(atom_nc, coords)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apps/apps/binapps/pytorch/2.3.0/python3.11/gpu-cuda12.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apps/apps/binapps/pytorch/2.3.0/python3.11/gpu-cuda12.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/iusers01/rb01/m60623zk/bin/PairNetOpsV3/network.py", line 285, in forward
    energy = self.ERecomposition(coords, unscale_E)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apps/apps/binapps/pytorch/2.3.0/python3.11/gpu-cuda12.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apps/apps/binapps/pytorch/2.3.0/python3.11/gpu-cuda12.1/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/iusers01/rb01/m60623zk/bin/PairNetOpsV3/network.py", line 181, in forward
    recompE = torch.einsum('bi, bi -> b', eij_E, decompFE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apps/apps/binapps/pytorch/2.3.0/python3.11/gpu-cuda12.1/lib/python3.11/site-packages/torch/functional.py", line 385, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: einsum(): subscript i has size 36 for operand 1 which does not broadcast with previously seen size 324
